doc/database.md, webapp/package.json, webapp/src/app/app.component.html, webapp/src/app/app.component.spec.ts, webapp/src/app/app.component.ts, webapp/src/app/app.module.ts, webapp/src/app/models/profile.ts, webapp/src/app/profile/profile.component.html, webapp/src/app/profile/profile.component.spec.ts, webapp/src/app/profile/profile.component.ts, webapp/src/app/types.ts, webapp/src/app/user.service.spec.ts, webapp/src/app/user.service.ts, webapp/yarn.lock
added Firebase Authentication and Realtime Database with Angular fire
login / logout buttons are shown depending on state
=> sets data in RTDB, basic auth

functions/index.js
Currently deployed at: https://us-central1-hubbub-159904.cloudfunctions.net/closeSlot
Expects a `POST` with a single form-encoded parameter in the body `id` which is the `id` of the slot that should get closed (and users matched).
=> Implement temporary version of `closeSlot` HTTP function

webapp/src/app/admin/admin.component.html, webapp/src/app/admin/admin.component.spec.ts, webapp/src/app/admin/admin.component.ts, webapp/src/app/admin/admin.module.ts, webapp/src/app/admin/admin.service.spec.ts, webapp/src/app/admin/admin.service.ts, webapp/src/app/app.component.css, webapp/src/app/app.component.html, webapp/src/app/app.component.spec.ts, webapp/src/app/app.module.ts, webapp/src/app/app.router.ts, webapp/src/app/lunch/lunch.component.html, webapp/src/app/lunch/lunch.component.spec.ts, webapp/src/app/lunch/lunch.component.ts, webapp/src/app/types.ts, webapp/src/app/user.service.spec.ts, webapp/src/styles.css
/admin displays list of slots
no actual admin role yet
=> Admin module with list of slots

webapp/src/app/admin/admin.component.html, webapp/src/app/admin/admin.component.spec.ts, webapp/src/app/admin/admin.component.ts, webapp/src/app/admin/admin.module.ts, webapp/src/app/app.module.ts, webapp/src/app/types.ts
not pretty, but just getting the framework in place
=> admin: display data for selected slot

functions/index.js, functions/package.json, functions/slots.js, functions/yarn.lock, webapp/src/app/admin/admin.component.spec.ts, webapp/src/app/admin/admin.component.ts, webapp/src/app/admin/admin.module.ts, webapp/src/app/app.component.ts
renamed 'topics' to 'assignments'
the UI isn't pretty but it works
in /admin
- select a slot
- click the close button
- look at the database for results
=> admin console lets you close a slot

webapp/src/app/app.component.css, webapp/src/app/app.component.html
=> admin: sidenav menu with logout button

functions/index.js
While #24 is under review and being worked on, this is a bare-bones untested implementation in order to unblock app progress.
=> Temporary implementation of updateProfile function

doc/database.md
to match code (rename we did on Sat)
=> schema doc: topics => assignments

webapp/src/app/admin/admin.component.ts, webapp/src/app/app.component.html, webapp/src/app/app.component.scss, webapp/src/app/app.module.ts, webapp/src/app/app.router.ts, webapp/src/app/lunch/lunch.component.html, webapp/src/app/lunch/lunch.component.ts, webapp/src/app/lunch/lunch.module.ts, webapp/src/app/lunch/upcoming-events/upcoming-events.component.html, webapp/src/app/lunch/upcoming-events/upcoming-events.component.spec.ts, webapp/src/app/lunch/upcoming-events/upcoming-events.component.ts, webapp/src/app/profile/profile.component.html, webapp/src/app/profile/profile.component.scss, webapp/src/app/profile/profile.component.spec.ts, webapp/src/app/profile/profile.component.ts, webapp/src/app/slot.service.ts, webapp/src/app/types.ts, webapp/src/app/user.service.spec.ts, webapp/src/app/user.service.ts
home screen shows events user has requested with status: pending or topic name
screen with checkboxes is now at /request (and in sidenav menu)
All the Hubbub in toolbar now takes you to home screen
fixes https://github.com/all-the-hubbub/hubbub/issues/31
it's not pretty, but seems to work.  Everything updates in real time!
=> Web: home screen shows events user has requested

functions/index.js, functions/slots.js
Will want to followup with a PR that renames files and variables, but just looking at these changes by themselves should be much easier to review for correctness.
=> Functions: slots --> events

doc/database.md, functions/slots.js, webapp/src/app/admin/admin.component.ts, webapp/src/app/admin/admin.service.ts, webapp/src/app/slot.service.ts
rename to match new DB schema
updated docs
=> webapp: slots -> events

README.md
badge shows latest build status for master branch with link to Travis CI
=> adding a Build Status indicator to README

functions/index.js, functions/slots.js, functions/test/user-test.js, functions/user.js
There was a timeout that was happening on updateProfile (even though it was actually updating the profile)
=> fix timeout, RTDB tests pass locally

webapp/src/assets/oauth.html
Remove origin from the redirect location so it works on any domain.
=> Update oauth.html to handle staging environment

database.rules.json, doc/database.md, functions/index.js, functions/middleware.js
Implement `middleware.adminOnly` which verifies that the requesting user has an `admin = true` flag on their `/account` entry.
Sorry about the diff, there were tabs in the file 😢
=> Admin Middleware

database.rules.json, doc/database.md
Make `/accounts/{uid}/profileNeedsUpdate` writable by `{uid}`, in preparation for #60
=> Rules: profileNeedsUpdate

webapp/src/app/app.module.ts, webapp/src/app/app.router.ts, webapp/src/app/loggedout.guard.ts
fixes https://github.com/all-the-hubbub/hubbub/issues/63
=> if logged in on /login or / then redirect to home

functions/test/githubbub-test.js, functions/test/setup.js, functions/test/user-test.js
Ideally tests wouldn't need an OAuth token, this is a stopgap to let PRs turn green on travis
=> skip tests if OAuth token isn't configured

webapp/src/assets/beacon.html
=> Choose one of eight bubs as the beacon, based on topicId.

webapp/src/app/app.module.ts, webapp/src/app/event/event.component.html, webapp/src/app/event/event.component.spec.ts, webapp/src/app/event/event.component.ts, webapp/src/app/lunch/lunch.component.html, webapp/src/app/lunch/lunch.component.spec.ts, webapp/src/app/lunch/lunch.component.ts, webapp/src/app/slot.service.ts, webapp/src/app/types.ts, webapp/src/app/upcoming-events/upcoming-events.component.html, webapp/src/styles.scss
- implement turning off checkbox in "Join an event" screen
- display event data on home screen and checkbox screen
=> checkboxes
